Repository avinashkranjan/logsuite, pull requests merged in 2024-06, with the labels that each got.

#27 Update README.md
  README.md
Labels: gssoc, level1

#29 Add light theme Landing page
  README.md
  light_theme-figma.md
Labels: gssoc, level2

#28 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1

#9 Implemented Screenshot Capture
  example/android/app/build.gradle
  example/android/app/src/main/AndroidManifest.xml
  example/ios/Flutter/Debug.xcconfig
  example/ios/Flutter/Release.xcconfig
  example/lib/main.dart
  example/lib/screens/HomePage.dart
  example/macos/Flutter/Flutter-Debug.xcconfig
  example/macos/Flutter/Flutter-Release.xcconfig
  example/macos/Flutter/GeneratedPluginRegistrant.swift
  example/pubspec.lock
  example/pubspec.yaml
  example/test/widget_test.dart
  lib/ScreenshotGallery.dart
  lib/logsuite.dart
  lib/screenshot_capture.dart
  pubspec.yaml
Labels: gssoc, level3

#18 Add New Documentation Template to Issues Template
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: gssoc, level1

#19 Auto-Comment on Raise new Issues
  .github/workflows/openIssues-Auto_comment.yml
Labels: gssoc, level1

#20 Implement Workflow for Auto-Commit on Issue Closure
  .github/workflows/close-issues_autoComment.yml
Labels: gssoc, level1
